---
- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:
    - name: Installing Linux Apps
      become: true
      apt:
        name: '{{ item }}'
        install_recommends: yes
        state: present
      loop:
          - virtualbox
          - vim
          - curl
          - wget

    - block:
        - name: Installing Vagrant 2.2.19
          become: true
          unarchive:
            src: "https://releases.hashicorp.com/vagrant/2.2.19/vagrant_2.2.19_linux_amd64.zip"
            dest: /usr/local/bin
            remote_src: yes

    - block:
        - name: Install Microsoft Key
          become: true
          apt_key:
            url: "https://packages.microsoft.com/keys/microsoft.asc"
            state: present
        - name: Install VSCode Repository
          become: true
          apt_repository:
            repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
            state: present
            filename: vscode
        - name: Install Visual Studio Code
          become: true
          apt:
            name: code
        - name: Install Virtual Studio Code Extensions
          shell:
            cmd: code --install-extension '{{ item }}'
          loop:
            - redhat.vscode-yaml
            - bbenoist.vagrant
            - hashicorp.terraform
            - foxundermoon.shell-format
            - eamodio.gitlens
            - pkief.material-icon-theme

    - block:
      - name: Install Google Key
        become: true
        apt_key: 
          url: 'https://dl.google.com/linux/linux_signing_key.pub'
          state: present
      - name: Install Google Repository
        become: true
        apt_repository:
          repo: 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main'
          state: present
          filename: google-chrome
      - name: Install Google Chrome
        become: true
        apt:
          name: google-chrome-stable
